BiocManager::install("airway")
library(airway)
data(airway)
a
airway$dex=relevel(airway$dex,"untrt")
airway
airway$dex
round(colSums(assay(airway))/1e6,1)
colData(airway)
table(airway$cell)
table(airway$dex)
library(DESeq2)
dds=DESeqDataSet(airway,design = ~cell+dex)
dds
keep=rowSums(counts(dds)>=5)>=4
table(keep)
dds=dds[keep,]
boxplot(log10(counts(dds)+1),las=2)
dds=estimateSizeFactors(dds)
boxplot(log10(counts(dds,normalize=T)+1),las=2)
vsd=vst(dds)
class(vsd)
assay(vsd)[1:3,1:3]
plotPCA(vsd,"dex")
library(ggplot2)
pcadata=plotPCA(vsd,intgroup=c("dex","cell"),returnData=T)
percentvar=round(100*attr(pcadata,"percentVar"))
ggplot(pcadata,aes(x=PC1,y=PC2,color=dex,shape=cell))+geom_point(size=3)
dds=DESeq(dds)
res=results(dds)
head(res[order(res$pvalue),])
plotCounts(dds,which.min(res$pvalue),"dex")
plotMA(res,ylim=c(-5,5))
BiocManager::install("apeglm")
library(apeglm)
resultsNames(dds)
res2=lfcShrink(dds,coef = 'dex_trt_vs_untrt',type='apeglm')
par(mfrow=c(1,2))
plotMA(res,ylim=c(-3,3),main="no shrinkage")
plotMA(res2,ylim=c(-3,3),main="apeglm")
res.lfc=results(dds,lfcThreshold = 1)
res.lfc2=lfcShrink(dds,coef="dex_trt_vs_untrt",type="apeglm",lfcThreshold = 1)
par(mfrow=c(1,2))
plotMA(res.lfc,ylim=c(-5,5),main="no shrinkage")
plotMA(res.lfc2,ylim=c(-5,5),main="apeglm")
BiocManager::install("ReportingTools")
library(ReportingTools)
rep=HTMLReport(shortName = "airway",title="airway DGE",basePath = getwd(),reportDirectory = "report")
rep
publish(res,rep,dds,n=20,make.plots=T,factor=dds$dex)
finish(rep)
BiocManager::install("splatter")
library(splatter)
params=newSplatParams()
params=setParam(params,"de.facLoc",1)
params=setParam(params,"de.facScale",0.25)
params=setParam(params,"dropout.type","experiment")
params=setParam(params,"dropout.mid",3)
set.seed(1)
sim=splatSimulate(params,group.prob=c(0.5,0.5),method="groups")
plot(log10(rowMeans(assays(sim)[["TrueCounts"]])),rowMeans(assays(sim)[["Dropout"]]))
head(sim)
rowData(sim)$log2Fc=with(rowData(sim),log2(DEFacGroup2/DEFacGroup1))
head(assay(sim))
rowData(sim)$trueDisp=rowMeans(assays(sim)[["BCV"]])^2
gridlines=c(1e-2,1e-1,1)
1e-2
cols=c("blue","red","darkgreen")
with(rowData(sim)[rowData(sim)$GeneMean>1,],plot(GeneMean,trueDisp,log="xy",xlim=c(1,300),ylim=c(0.01,5)))
abline(h=gridlines,col=cols)
text(300,gridlines,labels = gridlines,col=cols,pos=3)
BiocManager::install("zinbwave")
library(zinbwave)
keep=rowSums(counts(sim)>=5)>=25
table(keep)
length(keep)
zinb=sim[keep,]
zinb$condition=factor(zinb$Group)
nms=c("counts",setdiff(assayNames(zinb),"counts"))
nms
assayNames(zinb)
assays(zinb)=assays(zinb)[nms]
zinb
assays(zinb)
zinb=zinbwave(zinb,K=0,epsilon=1e12)
warnings()
library(stats)
zdds=DESeqDataSet(zinb,design=~condition)
zdds=DESeq(zdds,test="LRT",reduced = ~1,sfType = "poscounts",minmu = 1e-6,minRep=Inf)
plotDispEsts(zdds)
keepfordisp=rowSums(counts(zdds)>=10)>=25
zdds2=estimateDispersionsFit(zdds[keepfordisp,])
plotDispEsts(zdds2)
zdds
result=results(zdds)
head(result)
